yumcron_download_updates: 'yes'
yumcron_apply_updates:
  hourly: 'no'
  daily: 'yes'

# Settings for EC2 instance
botinstance_region: us-west-1
botinstance_volume_size: 200
botinstance_type: t3.xlarge