yumcron_download_updates: 'yes'
yumcron_apply_updates:
  hourly: 'no'
  daily: 'yes'

# Settings for EC2 instance
botinstance_name: ansibullbot-community
botinstance_region: us-west-1
botinstance_volume_size: 200
botinstance_type: t3.xlarge
botinstance_ssh_keys:
  - name: tkuratomi
    key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQDfgKJEBuHFlFc8/IHDeIpdprNnAFQHkicXAFfAzIJSkhUaOJFjsulmgPZn2TJJpYqFAxYUjhWJOdrOwx7AHSg6gWu4TT4a0sTay+Z0eqZOShf5UL/M587DxJk1JZU8g812yDKZMc7Sv7K6zdteONnCvno1kALSg0F2MVMJXFjE/tSontkIRH6IuG19R19NGEj1h56uGwdfe78xjOmv5wk6RZBjaOKqiPSQKNqCKbY9Kyz6yrem2M5uxRK45u3wSPJdmopo8l/nwf0p6ydrUSL5C/aXGh7LPqh31eTBDQUbWHw9LQMk1SibMGQPwJt59lLMlzc5OQZAJEbadsDAgl6VVA6MZkBQROiK9E087kvPesMoGWE0KBgvTqzpBZj0uHATP9i097dv80gjupMyaePsnQOxk0wRho9nRkxRo18Drt3QPVND4YGHzahMe/YR2N83MkbnGoP8K+GsFhLMAp3NKh6yUofFxTgRiB6H8ULKf3CV+hlk0Z9RJR3CpgMTKILYHPlaleJqoP6sXg6tJxI0rUE+0jUKvaTj+N2gX0MjKfUINk5mTbjD2mdVrPtKOBvos2luNhY5nTDpJuAHQqnFHPlPw8l3lXC2VBWOjqfTeeS+qD7ArKe6F7IO5ZNxJ2mTUuodhaPySta1MS37DWoz6UqeJu+wKIsHok90+EU4aAvUABh3RXSQA1E3IaxkooMhhrdIQO6K4L0M+CZ7lP35sW5pnwsN4sFlPec9Xn5e15LTlb9yFlx7Nm4DE2SX1s9QyMRE7z0LNO0X7wiihojuyQM6OQwc+ZaaDw5HerBisX/3LcC9osVLQQg1pt91YcCczUQ08qfUJV6aOD962K+EGzVFQGGauJDzgEH9BHQg7QwCWr0f3mu8/TNBzys2c0YsywDUc3AT1KP6TEJcR/dy6WbhJD3qyO/BLfCzRrHUOIaz+WbwmfTX8tGEQnVV5sEkZ39PWA1hRQ83b3MNV8cRJl+h/FnTk62yM4ZqGu73+x8JiEG3HAJp9/xYfNSwg8++PojJBXe+yM6DrTh5fTnBhxatLEKB658p8jTqJtF4+YD9D8+L39xEns6GQ7FphNqTC6IcpXyqq+zNuzF7vs/T+5n7978dUs3sK6YpBX4BlDxK6MsRF1WYqajEVeBJEMwdX2rfGkN9B5GfWdmdrzBjZQ6yyvlx5Dg++qgxpMiVOXSnw5v7H03PrT1we9wKre/2SQ1A2Oq/UDt/7tR2cMLoaPDNBpFT1W44LJB7o9iDT9YHUG3dC7R8JoeJ5YjyFmxbUQ5xg1oHnrBaPrGCuEYdQWhuDmp9Px2yRu8Agxzr9rNCZ/W8nWJVmvwvlXoldrum2rAECx0wiWqBhQ/+eX65'

  - name: sdoran@aws_work
    key_material: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfJ88NuTDKSpYq+wrDCd+AKg2l1jqg0qgXxjiNXwaEUOUllb5II0uin7xh/6jl9hLRbwVOe/CjD+tjbb7IAuno6B/Nx4CqybArYv7w+GHH0fSrpLpojGzuO9IJ/p1Rxw7vum5INAQ9tPHScF2CwoANsYpmU1sgC+lzd3frobTOsQ9Gj/jEh6I2Ugvm3N0Xjd4IA2788zsmOD/viHQt47AVOqFGhkyt/QlFdxw2MqUevkQiEmIv46aZkSLMtcsoLa/q63tCVaEl8vRRWhUVei8fvs5mVcPuJzq8jV92mtU+JUzh+SRpKynUsQKME4OB3OgUpTtpZvAJONWY4NS8P9t5

  - name: jtanner
    key_material: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8FEp2Kr8lD0Sp7kfbUWWHTT/ilD0Tup2Wh8K1HGN8usZk4O6dAVZJHUp35DcCj8JV5l5zrdO7o+PHvlkYigC/y/17dsAsTC0MZeHAA0p8aFhJv08+l8JF4WIAt34OrMZ2UePblO27/XTIm6MvynBye6BwDQ/GFQKebPyU4GBamy9IIqW1RCupMj6P04GYDGpQMjYTgtHZD5xstUFWxs0ybEvbpQZglGNuD6E7+8xApqZrMX6hgFglWmxMPzJZxIirzZ/TWRW0eEZ7r468I5HJcFGO8/qe1xBv8BYWGFt9L6tVNTLi9gI3lbxv87O0ksQ2c37nBvZ+2h2xQoIJDkuf

  - name: tower2_deploy
    key_material: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk3j+kA6cfWin+Gq7RWZ1JQdpTbwEwpDPMN2GZy3uksDKnG8c+lXvfXhrtJ1XtQQmta06J8oEp4pmf8QlFflftxoq/LRJ/YlmviSzvWbyqBYGtFo/Ndv0QU1UokY3jjLGiktvmmU7hH/xGDOBZLX9I2L/A0WiJ9HoAkKUGPfQwokTpbwPlZ0U7zZ6ivqyRjnKmkzt6SkPExZ3JGIo5EfQoZMLRxyHmSvuTP+3dgNhTKGCbtQErPfU4tmL3u/1nz/7HoX1G0z8fee/QxgVCvWKmgbVXW28Vsyio8ekFqVmViZae4m8SgE4viR10fj2Gultmp17bwnG8RWPqJ0liY+4hplEfZ+p4awcR3n1f4vyPW0somE5TTzU2v0ze+mhj0DusIyblfqsBHOX55w2SVFW+rDB3rZ8MdN//JeYndFbLH69Sjggys+Yl9nUQ81sIo7LY4mdFzOOnn5wtBTzNf8NjwVn51jPh2XOg1AA2/QCnM7VweUfb3AqlrOCinTtySBz0eX75fbttyyGTYKGc4v8ZFDjFAxEl1ZxFmMP30LbCnAyc4Q2CQYp8BS1xxww9BXDQe+v91Z9NwYQNYTFDP0nMPh+yQOJdlSA1ZBZIAtH/Z92Uz0CwgFZLeAaWXBxwKO3IezLGLTboojr9m1Fm3/sCPSSHK9SURB4iAopdOXNW7Q==

  - name: mkrizek@x240
    key_material: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdIcSGGFCk4VLylSLCKHYoLK1vOEU9ebxJn5dtBY1MRAdEL7dDWzwfoovXzxkHWXOWYDWL2ayZJHUmFfN9JVAg20FYNitU+PZlZs/H8xuWNjL4SbgOq6oBbZAHQnQ5EO0N2rfOMJXC5XEqAEDZVfOvJJt9qcPoBizMFIiTRT/yU47QFo7z3SGCbuMOEE9wZU+VFX8KKwHp1jP37dvLNBh/bdUwvo6RTpk7aUN8zv3BvAjUeT/hC6bbqMw4ibvWp/HbzKHFPBWp5mimIr/j2AbFLnY+c9T2/MJ1FeJIDeNC+uNR/J12XD2WQyUp4QowCsZMCKEkhNDVtm05yM5n+OV9

botinstance_dns_entries:
  - type: CNAME
    record: ansibot-com.eng.ansible.com
    value: ansibullbot-com.eng.ansible.com

  - type: CNAME
    record: ansiblebot-com.eng.ansible.com
    value: ansibullbot-com.eng.ansible.com

  - type: A
    command: create
    record: ansibullbot-com.eng.ansible.com
    value: "{{ _elastic_ip.public_ip }}"
